version: "3"

services:

  node-api:
    build: ./question-answering-system-main-js-api
    container_name: node-api
    image: node-api
    restart: always
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=development
      - NMT_URL=http://nmt:6542
    networks:
      - back-tier
    depends_on: 
     - nmt

  front-end:
    build: ./qa-system-app
    container_name: frontend
    image: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://node-api:8000/
    networks:
      - front-tier
      - back-tier
    command:
      "npm run dev"
    depends_on: 
     - node-api

  nmt:
    build: ./question-answering-system-machine-learning-python-api
    container_name: nmt
    image: nmt
    restart: always
    ports:
      - '6542:6542'
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: